CRITICAL - 2022-05-02 17:41:09 --> Call to undefined function sire_url()
#0 C:\xampp\htdocs\system\View\View.php(210): include()
#1 C:\xampp\htdocs\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\system\Common.php(1089): CodeIgniter\View\View->render('view_home', Array, true)
#3 C:\xampp\htdocs\app\Controllers\Home.php(25): view('view_home', Array)
#4 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\Home->index()
#5 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-02 18:35:21 --> count(): Argument #1 ($var) must be of type Countable|array, null given
#0 C:\xampp\htdocs\system\View\View.php(210): include()
#1 C:\xampp\htdocs\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\system\Common.php(1089): CodeIgniter\View\View->render('view_cadastro_u...', Array, true)
#3 C:\xampp\htdocs\app\Controllers\cadastro_usuario.php(24): view('view_cadastro_u...', Array)
#4 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\cadastro_usuario->index()
#5 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cadastro_usuario))
#6 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-02 19:29:56 --> syntax error, unexpected identifier "editar", expecting variable
#0 C:\xampp\htdocs\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('cadastro_usuari...')
#1 C:\xampp\htdocs\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('cadastro_usuari...')
#2 C:\xampp\htdocs\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-02 19:30:54 --> Unclosed '{' on line 42 does not match ')'
#0 C:\xampp\htdocs\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('cadastro_usuari...')
#1 C:\xampp\htdocs\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('cadastro_usuari...')
#2 C:\xampp\htdocs\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-02 19:32:10 --> syntax error, unexpected variable "$id", expecting ")"
#0 C:\xampp\htdocs\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\mode...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\mode...')
#3 C:\xampp\htdocs\system\Config\Factories.php(136): class_exists('App\\Models\\mode...')
#4 C:\xampp\htdocs\system\Config\Factories.php(106): CodeIgniter\Config\Factories::locateClass(Array, 'model_cadastro_...')
#5 C:\xampp\htdocs\system\Common.php(780): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 C:\xampp\htdocs\app\Controllers\cadastro_usuario.php(20): model('model_cadastro_...')
#7 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\cadastro_usuario->index()
#8 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cadastro_usuario))
#9 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-05-02 19:32:53 --> syntax error, unexpected variable "$id", expecting ")"
#0 C:\xampp\htdocs\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\mode...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\mode...')
#3 C:\xampp\htdocs\system\Config\Factories.php(136): class_exists('App\\Models\\mode...')
#4 C:\xampp\htdocs\system\Config\Factories.php(106): CodeIgniter\Config\Factories::locateClass(Array, 'model_cadastro_...')
#5 C:\xampp\htdocs\system\Common.php(780): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 C:\xampp\htdocs\app\Controllers\cadastro_usuario.php(20): model('model_cadastro_...')
#7 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\cadastro_usuario->index()
#8 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cadastro_usuario))
#9 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-05-02 19:32:54 --> syntax error, unexpected variable "$id", expecting ")"
#0 C:\xampp\htdocs\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\mode...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\mode...')
#3 C:\xampp\htdocs\system\Config\Factories.php(136): class_exists('App\\Models\\mode...')
#4 C:\xampp\htdocs\system\Config\Factories.php(106): CodeIgniter\Config\Factories::locateClass(Array, 'model_cadastro_...')
#5 C:\xampp\htdocs\system\Common.php(780): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 C:\xampp\htdocs\app\Controllers\cadastro_usuario.php(20): model('model_cadastro_...')
#7 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\cadastro_usuario->index()
#8 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cadastro_usuario))
#9 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-05-02 19:33:15 --> syntax error, unexpected token "="
#0 C:\xampp\htdocs\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\mode...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\mode...')
#3 C:\xampp\htdocs\system\Config\Factories.php(136): class_exists('App\\Models\\mode...')
#4 C:\xampp\htdocs\system\Config\Factories.php(106): CodeIgniter\Config\Factories::locateClass(Array, 'model_cadastro_...')
#5 C:\xampp\htdocs\system\Common.php(780): CodeIgniter\Config\Factories::__callStatic('models', Array)
#6 C:\xampp\htdocs\app\Controllers\cadastro_usuario.php(20): model('model_cadastro_...')
#7 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\cadastro_usuario->index()
#8 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cadastro_usuario))
#9 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-05-02 19:43:01 --> syntax error, unexpected token "%"
#0 C:\xampp\htdocs\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\system\Common.php(1089): CodeIgniter\View\View->render('view_cadastro_u...', Array, true)
#2 C:\xampp\htdocs\app\Controllers\cadastro_usuario.php(53): view('view_cadastro_u...', Array)
#3 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\cadastro_usuario->editar('1')
#4 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cadastro_usuario))
#5 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-02 20:06:13 --> syntax error, unexpected token "echo"
#0 C:\xampp\htdocs\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\system\Common.php(1089): CodeIgniter\View\View->render('view_cadastro_u...', Array, true)
#2 C:\xampp\htdocs\app\Controllers\cadastro_usuario.php(53): view('view_cadastro_u...', Array)
#3 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\cadastro_usuario->editar('1')
#4 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cadastro_usuario))
#5 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-02 20:06:29 --> syntax error, unexpected token "echo"
#0 C:\xampp\htdocs\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\system\Common.php(1089): CodeIgniter\View\View->render('view_cadastro_u...', Array, true)
#2 C:\xampp\htdocs\app\Controllers\cadastro_usuario.php(53): view('view_cadastro_u...', Array)
#3 C:\xampp\htdocs\system\CodeIgniter.php(832): App\Controllers\cadastro_usuario->editar('1')
#4 C:\xampp\htdocs\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cadastro_usuario))
#5 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-02 20:19:30 --> Cannot re-assign $this
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-02 20:22:57 --> Cannot re-assign $this
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-02 20:34:08 --> syntax error, unexpected token ";"
#0 C:\xampp\htdocs\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('cadastro_usuari...')
#1 C:\xampp\htdocs\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('cadastro_usuari...')
#2 C:\xampp\htdocs\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-02 20:34:35 --> syntax error, unexpected token "else"
#0 C:\xampp\htdocs\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('cadastro_usuari...')
#1 C:\xampp\htdocs\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('cadastro_usuari...')
#2 C:\xampp\htdocs\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-02 20:38:20 --> syntax error, unexpected token "else"
#0 C:\xampp\htdocs\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('cadastro_usuari...')
#1 C:\xampp\htdocs\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('cadastro_usuari...')
#2 C:\xampp\htdocs\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-02 20:38:39 --> syntax error, unexpected token ";"
#0 C:\xampp\htdocs\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('cadastro_usuari...')
#1 C:\xampp\htdocs\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('cadastro_usuari...')
#2 C:\xampp\htdocs\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-02 20:39:26 --> syntax error, unexpected token "public", expecting end of file
#0 C:\xampp\htdocs\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('cadastro_usuari...')
#1 C:\xampp\htdocs\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('cadastro_usuari...')
#2 C:\xampp\htdocs\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-02 20:42:20 --> syntax error, unexpected token "public", expecting end of file
#0 C:\xampp\htdocs\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('cadastro_usuari...')
#1 C:\xampp\htdocs\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('cadastro_usuari...')
#2 C:\xampp\htdocs\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-02 20:42:45 --> Cannot re-assign $this
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
